export const LOADING = 'LOADING';
export const SET_FAVORITE_IMAGE_INFO = 'SET__FAVORITE_IMAGE_INFO';
export const SET_DATE = 'SET_DATE';
export const REMOVE_FAVORITE_IMAGE_INFO = 'REMOVE_FAVORITE_IMAGE_INFO';
export const SET_CURRENT_DAY_IMAGE = 'SET_CURRENT_DAY_IMAGE'
export const GET_IMAGE_FAILED = 'GET_IMAGE_FAILED'
export const SET_NEXT_IMAGE = 'SET_NEXT_IMAGE'
export const SET_PREV_IMAGE = 'SET_PREV_IMAGE'
export const SET_USER_ID = 'SET_USER_ID'



